set echo on
SPOOL vfc_schema_output.txt

-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-19 01:22:58 AEDT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
--   stu_id:    36705691
--   stu_name:  Dylan Collaga

DROP TABLE assessment CASCADE CONSTRAINTS;

DROP TABLE centre CASCADE CONSTRAINTS;

DROP TABLE class CASCADE CONSTRAINTS;

DROP TABLE class_attendance CASCADE CONSTRAINTS;

DROP TABLE class_enrolment CASCADE CONSTRAINTS;

DROP TABLE class_leader CASCADE CONSTRAINTS;

DROP TABLE class_staff CASCADE CONSTRAINTS;

DROP TABLE class_type CASCADE CONSTRAINTS;

DROP TABLE facility CASCADE CONSTRAINTS;

DROP TABLE member CASCADE CONSTRAINTS;

DROP TABLE staff CASCADE CONSTRAINTS;

DROP TABLE staff_role CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE assessment (
   member_num          NUMBER(8) NOT NULL,
   assess_date         DATE NOT NULL,
   member_weight       NUMBER(5,2),
   member_sysbloodpres NUMBER(3),
   member_diabloodpres NUMBER(3),
   member_bmi          NUMBER(3,1),
   member_vo2          NUMBER(3,1),
   assessor_staff_id   NUMBER(4) NOT NULL
);

COMMENT ON COLUMN assessment.member_num IS
   'Member number';

COMMENT ON COLUMN assessment.assess_date IS
   'Assessment date';

COMMENT ON COLUMN assessment.member_weight IS
   'Member weight in kilograms from assessment';

COMMENT ON COLUMN assessment.member_sysbloodpres IS
   'Member systolic blood pressure from assessment';

COMMENT ON COLUMN assessment.member_diabloodpres IS
   'Member diastolic blood pressure from assessment';

COMMENT ON COLUMN assessment.member_bmi IS
   'Member BMI from assessment';

COMMENT ON COLUMN assessment.member_vo2 IS
   'Member VO2 max from assessment';

COMMENT ON COLUMN assessment.assessor_staff_id IS
   'Staff ID';

ALTER TABLE assessment ADD CONSTRAINT assessment_pk PRIMARY KEY ( member_num,
                                                                  assess_date );

CREATE TABLE centre (
   centre_id            NUMBER(2) NOT NULL,
   centre_name          VARCHAR2(20) NOT NULL,
   centre_streetaddress VARCHAR2(80) NOT NULL,
   centre_suburb        VARCHAR2(40) NOT NULL,
   centre_state         CHAR(3) NOT NULL,
   centre_postcode      NUMBER(4) NOT NULL,
   centre_phone         CHAR(10) NOT NULL,
   manager_staff_id     NUMBER(4) NOT NULL
);

ALTER TABLE centre
   ADD CONSTRAINT chk_centre_state_addr
      CHECK ( centre_state IN ( 'ACT',
                                'NSW',
                                'NT',
                                'QLD',
                                'SA',
                                'TAS',
                                'VIC',
                                'WA' ) );

COMMENT ON COLUMN centre.centre_id IS
   'Centre ID';

COMMENT ON COLUMN centre.centre_name IS
   'Name of centre';

COMMENT ON COLUMN centre.centre_streetaddress IS
   'Centre street address';

COMMENT ON COLUMN centre.centre_suburb IS
   'Centre suburb';

COMMENT ON COLUMN centre.centre_state IS
   'Centre state';

COMMENT ON COLUMN centre.centre_postcode IS
   'Centre postcode';

COMMENT ON COLUMN centre.centre_phone IS
   'Contact phone number of centre';

COMMENT ON COLUMN centre.manager_staff_id IS
   'Staff ID';
CREATE UNIQUE INDEX centre__idx ON
   centre (
      manager_staff_id
   ASC );

ALTER TABLE centre ADD CONSTRAINT centre_pk PRIMARY KEY ( centre_id );

CREATE TABLE class (
   class_num             NUMBER(2) NOT NULL,
   centre_id             NUMBER(2) NOT NULL,
   class_startdatetime   DATE NOT NULL,
   class_duration        NUMBER(3) NOT NULL,
   class_capacity        NUMBER(2) NOT NULL,
   class_session_count   NUMBER(3) NOT NULL,
   class_cost            NUMBER(5,2) NOT NULL,
   class_gender_restrict CHAR(1) NOT NULL,
   class_type            VARCHAR2(20) NOT NULL,
   class_fac_room_num    NUMBER(2) NOT NULL,
   class_fac_centre_id   NUMBER(2) NOT NULL
);

ALTER TABLE class
   ADD
      CHECK ( class_gender_restrict IN ( 'F',
                                         'M',
                                         'U' ) );

COMMENT ON COLUMN class.class_num IS
   'Class number';

COMMENT ON COLUMN class.centre_id IS
   'Centre ID';

COMMENT ON COLUMN class.class_startdatetime IS
   'First class session date/time';

COMMENT ON COLUMN class.class_duration IS
   'Class duration in minutes';

COMMENT ON COLUMN class.class_capacity IS
   'Maximum number of participants in class';

COMMENT ON COLUMN class.class_session_count IS
   'Total count of run class sessions (max 999)';

COMMENT ON COLUMN class.class_cost IS
   'Cost of class for members';

COMMENT ON COLUMN class.class_gender_restrict IS
   'Class gender restriction (U = Unrestricted, M = Male Only, F = Female Only)';

COMMENT ON COLUMN class.class_type IS
   'Class type';

COMMENT ON COLUMN class.class_fac_room_num IS
   'Facility room number';

COMMENT ON COLUMN class.class_fac_centre_id IS
   'Centre ID';

ALTER TABLE class ADD CONSTRAINT class_pk PRIMARY KEY ( class_num,
                                                        centre_id );

CREATE TABLE class_attendance (
   ca_id              NUMBER(7) NOT NULL,
   centre_id          NUMBER(2) NOT NULL,
   class_num          NUMBER(2) NOT NULL,
   member_num         NUMBER(8) NOT NULL,
   class_session_date DATE NOT NULL,
   class_attend_count NUMBER(5) NOT NULL
);

COMMENT ON COLUMN class_attendance.ca_id IS
   'Class attendence ID (SK)';

COMMENT ON COLUMN class_attendance.centre_id IS
   'Centre ID';

COMMENT ON COLUMN class_attendance.class_num IS
   'Class number';

COMMENT ON COLUMN class_attendance.member_num IS
   'Member number';

COMMENT ON COLUMN class_attendance.class_session_date IS
   'Class session date';

COMMENT ON COLUMN class_attendance.class_attend_count IS
   'Number of times member attended class';

ALTER TABLE class_attendance ADD CONSTRAINT class_attend_pk PRIMARY KEY ( ca_id );

ALTER TABLE class_attendance
   ADD CONSTRAINT class_attend_nkey UNIQUE ( class_num,
                                             member_num,
                                             class_session_date,
                                             centre_id );

CREATE TABLE class_enrolment (
   ce_id          NUMBER(7) NOT NULL,
   centre_id      NUMBER(2) NOT NULL,
   class_num      NUMBER(2) NOT NULL,
   member_num     NUMBER(8) NOT NULL,
   class_pay_date DATE,
   class_pay_amt  NUMBER(5,2)
);

COMMENT ON COLUMN class_enrolment.ce_id IS
   'Class enrolment ID (SK)';

COMMENT ON COLUMN class_enrolment.centre_id IS
   'Centre ID';

COMMENT ON COLUMN class_enrolment.class_num IS
   'Class number';

COMMENT ON COLUMN class_enrolment.member_num IS
   'Member number';

COMMENT ON COLUMN class_enrolment.class_pay_date IS
   'Class session date';

COMMENT ON COLUMN class_enrolment.class_pay_amt IS
   'Class payment amount';

ALTER TABLE class_enrolment ADD CONSTRAINT class_enrol_pk PRIMARY KEY ( ce_id );

ALTER TABLE class_enrolment
   ADD CONSTRAINT class_enrol_nkey UNIQUE ( class_num,
                                            member_num,
                                            centre_id );

CREATE TABLE class_leader (
   class_leader_staff_id NUMBER(4) NOT NULL
);

COMMENT ON COLUMN class_leader.class_leader_staff_id IS
   'Staff ID';

ALTER TABLE class_leader ADD CONSTRAINT class_leader_staff_id_pk PRIMARY KEY ( class_leader_staff_id );

CREATE TABLE class_staff (
   cs_id     NUMBER(4) NOT NULL,
   staff_id  NUMBER(4) NOT NULL,
   class_num NUMBER(2) NOT NULL,
   centre_id NUMBER(2) NOT NULL
);

COMMENT ON COLUMN class_staff.cs_id IS
   'Class staff ID (SK)';

COMMENT ON COLUMN class_staff.staff_id IS
   'Staff ID';

COMMENT ON COLUMN class_staff.class_num IS
   'Class number';

COMMENT ON COLUMN class_staff.centre_id IS
   'Centre ID';

ALTER TABLE class_staff ADD CONSTRAINT class_staff_pk PRIMARY KEY ( cs_id );

ALTER TABLE class_staff
   ADD CONSTRAINT class_staff_nkey UNIQUE ( staff_id,
                                            class_num,
                                            centre_id );

CREATE TABLE class_type (
   class_type VARCHAR2(20) NOT NULL,
   class_desc VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN class_type.class_type IS
   'Class type';

COMMENT ON COLUMN class_type.class_desc IS
   'Class name or description';

ALTER TABLE class_type ADD CONSTRAINT class_type_pk PRIMARY KEY ( class_type );

CREATE TABLE facility (
   fac_room_num  NUMBER(2) NOT NULL,
   fac_centre_id NUMBER(2) NOT NULL,
   fac_name      VARCHAR2(20) NOT NULL,
   fac_desc      VARCHAR2(20) NOT NULL,
   fac_capacity  NUMBER(2) NOT NULL
);

COMMENT ON COLUMN facility.fac_room_num IS
   'Facility room number';

COMMENT ON COLUMN facility.fac_centre_id IS
   'Centre ID';

COMMENT ON COLUMN facility.fac_name IS
   'Name of facility';

COMMENT ON COLUMN facility.fac_desc IS
   'Description of facility';

COMMENT ON COLUMN facility.fac_capacity IS
   'The maximum number of participants a facility can accommodate';

ALTER TABLE facility ADD CONSTRAINT facility_pk PRIMARY KEY ( fac_room_num,
                                                              fac_centre_id );

CREATE TABLE member (
   member_num           NUMBER(8) NOT NULL,
   member_givname       VARCHAR2(20),
   member_famname       VARCHAR2(20),
   member_streetaddress VARCHAR2(80) NOT NULL,
   member_suburb        VARCHAR2(40) NOT NULL,
   member_state         CHAR(3) NOT NULL,
   member_postcode      CHAR(4) NOT NULL,
   member_phone         CHAR(10) NOT NULL,
   member_joindate      DATE NOT NULL,
   home_centre_id       NUMBER(2) NOT NULL,
   referrer_member_num  NUMBER(8) NOT NULL
);

ALTER TABLE member
   ADD CONSTRAINT chk_member_state_addr
      CHECK ( member_state IN ( 'ACT',
                                'NSW',
                                'NT',
                                'QLD',
                                'SA',
                                'TA',
                                'VIC',
                                'WA' ) );

COMMENT ON COLUMN member.member_num IS
   'Member number';

COMMENT ON COLUMN member.member_givname IS
   'Member given name';

COMMENT ON COLUMN member.member_famname IS
   'Member family name';

COMMENT ON COLUMN member.member_streetaddress IS
   'Member street address';

COMMENT ON COLUMN member.member_suburb IS
   'Member address suburb';

COMMENT ON COLUMN member.member_state IS
   'Member address state';

COMMENT ON COLUMN member.member_postcode IS
   'Member address postcode';

COMMENT ON COLUMN member.member_phone IS
   'Member contact phone number';

COMMENT ON COLUMN member.member_joindate IS
   'Member contact phone number';

COMMENT ON COLUMN member.home_centre_id IS
   'Centre ID';

COMMENT ON COLUMN member.referrer_member_num IS
   'Member number';

ALTER TABLE member ADD CONSTRAINT member_pk PRIMARY KEY ( member_num );

CREATE TABLE staff (
   staff_id                    NUMBER(4) NOT NULL,
   staff_givname               VARCHAR2(20),
   staff_famname               VARCHAR2(20),
   staff_phone                 CHAR(10) NOT NULL,
   staff_datestarted           DATE NOT NULL,
   staff_is_firstaid_qualified CHAR(1) DEFAULT 'N' NOT NULL,
   centre_id                   NUMBER(2) NOT NULL,
   staff_role_code             NUMBER(2) NOT NULL
);

ALTER TABLE staff
   ADD CONSTRAINT chk_firstaid_qualified CHECK ( staff_is_firstaid_qualified IN ( 'N',
                                                                                  'Y' ) );

COMMENT ON COLUMN staff.staff_id IS
   'Staff ID';

COMMENT ON COLUMN staff.staff_givname IS
   'Staff given name';

COMMENT ON COLUMN staff.staff_famname IS
   'Staff family name';

COMMENT ON COLUMN staff.staff_phone IS
   'Staff contact phone number';

COMMENT ON COLUMN staff.staff_datestarted IS
   'Staff date started';

COMMENT ON COLUMN staff.staff_is_firstaid_qualified IS
   'Is staff first aid qualified? (Y/N)';

COMMENT ON COLUMN staff.centre_id IS
   'Centre ID';

COMMENT ON COLUMN staff.staff_role_code IS
   'Staff role code';

ALTER TABLE staff ADD CONSTRAINT staff_pk PRIMARY KEY ( staff_id );

CREATE TABLE staff_role (
   staff_role_code NUMBER(2) NOT NULL,
   staff_role_desc VARCHAR2(50) NOT NULL
);

ALTER TABLE staff_role
   ADD CONSTRAINT chk_staff_code
      CHECK ( staff_role_code IN ( 'A',
                                   'C',
                                   'D',
                                   'M',
                                   'P',
                                   'S',
                                   'T' ) );

COMMENT ON COLUMN staff_role.staff_role_code IS
   'Staff role code';

COMMENT ON COLUMN staff_role.staff_role_desc IS
   'Staff role description';

ALTER TABLE staff_role ADD CONSTRAINT staff_role_pk PRIMARY KEY ( staff_role_code );

ALTER TABLE class
   ADD CONSTRAINT centre_class_fk FOREIGN KEY ( centre_id )
      REFERENCES centre ( centre_id );

ALTER TABLE facility
   ADD CONSTRAINT centre_fac_fk FOREIGN KEY ( fac_centre_id )
      REFERENCES centre ( centre_id );

ALTER TABLE centre
   ADD CONSTRAINT centre_manager_fk FOREIGN KEY ( manager_staff_id )
      REFERENCES staff ( staff_id );

ALTER TABLE staff
   ADD CONSTRAINT centre_staff_fk FOREIGN KEY ( centre_id )
      REFERENCES centre ( centre_id );

ALTER TABLE class_attendance
   ADD CONSTRAINT class_class_attend_fk
      FOREIGN KEY ( class_num,
                    centre_id )
         REFERENCES class ( class_num,
                            centre_id );

ALTER TABLE class_enrolment
   ADD CONSTRAINT class_enrol_fk
      FOREIGN KEY ( class_num,
                    centre_id )
         REFERENCES class ( class_num,
                            centre_id );

ALTER TABLE class
   ADD CONSTRAINT class_fac_fk
      FOREIGN KEY ( class_fac_room_num,
                    class_fac_centre_id )
         REFERENCES facility ( fac_room_num,
                               fac_centre_id );

ALTER TABLE class_leader
   ADD CONSTRAINT class_leader_fk FOREIGN KEY ( class_leader_staff_id )
      REFERENCES staff ( staff_id );

ALTER TABLE class_staff
   ADD CONSTRAINT class_staff_class_fk
      FOREIGN KEY ( class_num,
                    centre_id )
         REFERENCES class ( class_num,
                            centre_id );

ALTER TABLE class
   ADD CONSTRAINT class_type_class_fk FOREIGN KEY ( class_type )
      REFERENCES class_type ( class_type );

ALTER TABLE member
   ADD CONSTRAINT homecentre_fk FOREIGN KEY ( home_centre_id )
      REFERENCES centre ( centre_id );

ALTER TABLE assessment
   ADD CONSTRAINT member_assess_fk FOREIGN KEY ( member_num )
      REFERENCES member ( member_num );

ALTER TABLE class_attendance
   ADD CONSTRAINT member_class_attend_fk FOREIGN KEY ( member_num )
      REFERENCES member ( member_num );

ALTER TABLE class_enrolment
   ADD CONSTRAINT member_class_enrol_fk FOREIGN KEY ( member_num )
      REFERENCES member ( member_num );

ALTER TABLE member
   ADD CONSTRAINT member_referral_fk FOREIGN KEY ( referrer_member_num )
      REFERENCES member ( member_num );

ALTER TABLE assessment
   ADD CONSTRAINT staff_assess_fk FOREIGN KEY ( assessor_staff_id )
      REFERENCES staff ( staff_id );

ALTER TABLE staff
   ADD CONSTRAINT staff_role_fk FOREIGN KEY ( staff_role_code )
      REFERENCES staff_role ( staff_role_code );

ALTER TABLE class_staff
   ADD CONSTRAINT staff_staff_class_fk FOREIGN KEY ( staff_id )
      REFERENCES staff ( staff_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             1
-- ALTER TABLE                             38
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
SPOOL off
set echo off